### ISSUE TITLE
Some PNG files fail to load

### ISSUE THREAD

**Issue by stiv-yakovenko** [lukeapage/pngjs2#21]
This piece of code:

var fs = require('fs');
PNG = require('pngjs2').PNG;

var dst = new PNG({filterType: -1, width: 100, height: 50});
fs.createReadStream('./logs/rid12.png')
    .pipe(new PNG({
        filterType: -1
    }))
    .on('parsed', function() {
        this.bitblt(dst, 0, 0, 100, 50, 0, 0);
        dst.pack().pipe(fs.createWriteStream('out.png'));
    });

gives following error:

Error: Unrecognised filter type - 255
    at Filter._reverseFilterLine (c:\Users\stiv\Dropbox\Projects\canvasjs\Clients.dev\Editor\trunk\node_modules\pngjs2\lib\filter-parse.js:147:15)
    at ChunkStream._processRead (c:\Users\stiv\Dropbox\Projects\canvasjs\Clients.dev\Editor\trunk\node_modules\pngjs2\lib\chunkstream.js:174:13)
    at ChunkStream._process (c:\Users\stiv\Dropbox\Projects\canvasjs\Clients.dev\Editor\trunk\node_modules\pngjs2\lib\chunkstream.js:193:14)
    at ChunkStream.write (c:\Users\stiv\Dropbox\Projects\canvasjs\Clients.dev\Editor\trunk\node_modules\pngjs2\lib\chunkstream.js:61:8)

With attached file:
![rid12](https://cloud.githubusercontent.com/assets/4163254/9400467/51250d6a-47e3-11e5-9132-e5d0370922ed.png)

**Comment by lukeapage** [comment]
Thanks for reporting. Fixed and released in 1.0.1
